### ISSUE TITLE
kafka cluster support?

### ISSUE THREAD

**Issue by chiptip** [damiendallimore/SplunkModularInputsJavaFramework#8]
Does the splunk modular inputs connector supports kafka cluster with multiple zookeeper nodes?  Currently the splunk admin form accepts a zkhost and zkport separately and the java class is composing zookeeper.connect property based on the zkhost+":"+zkport.

https://github.com/damiendallimore/SplunkModularInputsJavaFramework/blob/master/kafka/src/com/splunk/modinput/kafka/KafkaModularInput.java#L174

multiple zk nodes usually is expressed in a form of "zkhost1:zkport,zkhost2:zkport,zkhost3:zkport", see zookeeper.connect under http://kafka.apache.org/documentation.html#brokerconfigs

**Comment by damiendallimore** [comment]
This has now been added.  See the latest release here https://splunkbase.splunk.com/app/1817/
